### PR TITLE
Allow Elements in arrow texts

### PR DESCRIPTION
**Pull request by carloscuesta**
Hello!

This PR, allows the use of React elements inside of `arrowLeftText` and `arrowRightText` props. Allowing the use of navigation icons for the Carousel.

Example: 

```language-javascript
import MaterialIcon from 'react-native-vector-icons/MaterialIcons'

<Carousel 
  arrows 
  leftArrowText={<MaterialIcon name={'keyboard-arrow-left'} />}
  rightArrowText={<MaterialIcon name={'keyboard-arrow-right'} />} >
</Carousel>
```

### CODE REVIEW

**Comment by sospedra** [comment]
+1 🙏

**Comment by carloscuesta** [comment]
Ping @phil-r

**Comment by phil-r** [comment]
Looks good!
Naming is a bit weird now, I think we'll need to rename `leftArrowText` to `leftArrow` and `rightArrowText` to `rightArrow` in the future

**Comment by vinhtq** [comment]
+ 1 for this

**Pull request merged**
