### PR TITLE
add swipe controll

### PR DESCRIPTION
**Pull request by satsuki0221**
When you want to prohibit control of swipe,
Added swipe of true or false for Props.
Since default props is set to true, there is no harm to existing users
We made it available only to users who want to use it.

### CODE REVIEW

**Comment by harshil07** [comment]
was looking for the same thing +1

**Comment by phil-r** [comment]
@satsuki0221 Thank you for PR, can you please resolve conflicts and I'll be happy to merge it

**Comment by satsuki0221** [comment]
Current master,
It was impossible to manipulate action with a swipe.
Do you understand the cause?

**Comment by viktorsec** [comment]
@satsuki0221 maybe related to #92

**Comment by satsuki0221** [comment]
about thinking that it is caused by deleting this._setContents (); from _onLayout...

**Comment by satsuki0221** [comment]
To rebuild newly

**Pull request closed without merging**
