### PR TITLE
Dynamic Content Length Of One

### PR DESCRIPTION
**Pull request by anders-g-hansen**
When using dynamically created content for the carousel which ends up being an array of length 1, the component was incorrectly adding the array a child instead of the 0th element.

```javascript
                    <Carousel
                        style={{width: 200, height: 200}}
                        autoplay={false}
                        bullets={true}
                        onAnimateNextPage={(p) => console.log(p)}>
                        { icons }
                    </Carousel>
```

### CODE REVIEW

**Comment by anders-g-hansen** [comment]
Fixes #64

**Comment by phil-r** [comment]
LGTM! Thanks for your contribution!

**Comment by HermitCarb** [comment]
Hei, I think It's not most appropriate commit:[00ed8d9](https://github.com/appintheair/react-native-looped-carousel/pull/66/commits/00ed8d99e4a74b6494b51fe0e6cdc26cc7e6ad78) #66 . Code will be crashed when this.props.children is an empty array.

**Comment by PhilipMortiboy** [comment]
@phil-r Any chance an update with this fix could be published to npm? 

Thanks

**Comment by ajonno** [comment]
I really need this too, if fix has been made can it be published ? thanks.

**Comment by ajonno** [comment]
any updates ??? please publish this fix.

**Pull request merged**
